apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database 
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"  # Hardcoded password from your data_sql.py
            - name: MYSQL_DATABASE
              value: "tasks_app"  # Hardcoded database name from your data_sql.py
            - name: MYSQL_USER
              value: "root"  # Hardcoded user from your data_sql.py
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database 
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
