---
# MySQL ConfigMap with transaction isolation setting
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database
data:
  my.cnf: | # This is the configuration file for MySQL
    [mysqld]
    transaction-isolation = READ-COMMITTED
---
# Application ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: application
data:
  DB_HOST: "mysql.database.svc.cluster.local"
  DB_USER: "root"
  DB_NAME: "todo_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  # Replace the value below with your base64-encoded secret key
  secret-key: YWxhZGRpbjpvcGVuc2VzYW1l
