apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-config
data:
  APP_ENV: "production"
  DATABASE_URL: "postgresql://user:pass@db:5432/contacts_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: contacts-secret
type: Opaque
data:
  # Replace the value below with your base64-encoded secret key
  secret-key: YWxhZGRpbjpvcGVuc2VzYW1l
