apiVersion: v1
kind: Service
metadata:
  name: contacts-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Uncomment and update the line below if you have allocated specific Elastic IPs:
    # service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-xxxxxxxx,eipalloc-yyyyyyyy"
spec:
  type: LoadBalancer
  ports:
    - port: 5053
      targetPort: 5053
      protocol: TCP
  selector:
    app: contacts
