apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: application
data:
  DB_HOST: "mysql.database.svc.cluster.local"
  DB_USER: "root"
  DB_NAME: "todo_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  # Replace the value below with your base64-encoded secret key
  secret-key: YWxhZGRpbjpvcGVuc2VzYW1l
