apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 5053
      targetPort: 5053
      protocol: TCP
  selector:
    app: todo-app
